[package]
name = "hugr_validator"
version = "0.4.0"
edition = "2021"

[dependencies]
hugr = "0.9.0"
serde_json = "*"
brat_extension = { path = "../hugr_extension" }
clap = { version = "4.5", features = ["derive"] }
clio = { version = "0.3.5", features = ["clap-parse"] }