name: Add issues to project board

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      # Old project
      # TODO: Remove once fully migrated to the new flow
      - uses: actions/add-to-project@v0.6.1
        with:
          project-url: https://github.com/orgs/quantinuum-dev/projects/10
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
      # New project
      - uses: actions/add-to-project@v0.6.1
        with:
          project-url: https://github.com/orgs/quantinuum/projects/23
          github-token: ${{ secrets.HUGRBOT_PAT }}
